### ISSUE TITLE
Add option to invoke via async route

### ISSUE THREAD

**Issue by alexellis** [openfaas-incubator/connector-sdk#1]
As a user I would like to consume events from a queue and then have them processed by my existing asynchronous queue workers over NATS Streaming so that I can have one single way to process all events and asynchronous code.

**Comment by daikeren** [comment]
@alexellis What's your preferred way of supporting async function? One possible solution might be add another annotation to function (maybe something like `async: true` ?) 

Is there any suggestion?

**Comment by alexellis** [comment]
cc @martindekov @tessellator 

@daikeren I think `async_invoke`  as an env-var would work.

**Comment by martindekov** [comment]
Derek assign: me

**Comment by martindekov** [comment]
I will try to implement this as soon as I can this time this week and will ping 👍

**Comment by alexellis** [comment]
Can you check the PR #27 please?

**Comment by martindekov** [comment]
Should I augment this PR to be optional the asynchronous or adding call to the asynchronous gateway path to the connector SDK?

**Comment by martindekov** [comment]
I was thinking of two approaches, amend the asynchronous path to where we configure the gateway URL so now its `http://your.ip:port` it would become `http://your.ip:port/async-function`/`http://your.ip:port/function/` this would be the easiest approach, the second approach would be to add some sort boolean to the ControllerConfig(I need to make sure thats the most appropriate place). The former would just re-vendor the SDK with this simple change `%s/function/%s` -> `%s/%s` and add logic to the implementations of the connector which will build the gateway URL with async/non-async path.
