### ISSUE TITLE
Gopkg.toml out of sync (pkg errors missing)

### ISSUE THREAD

**Issue by embano1** [openfaas-incubator/connector-sdk#11]
`package types` makes use of the `errors.Wrap` function, which is an external dependency:
https://github.com/openfaas-incubator/connector-sdk/blob/ed620ed7ce564746683ad24664a791eda6b1f693/types/invoker.go#L58

Neither Gopkg.toml nor *.lock specify this package.
This leads to problems contributing to this package as contributors could potentially add wrong package versions:

```bash
dep status
Gopkg.lock is out of sync with imports and/or Gopkg.toml. Run `dep check` for details.
PROJECT                MISSING PACKAGES
github.com/pkg/errors  [github.com/pkg/errors]
input-digest mismatch
```

**Comment by alexellis** [comment]
👍 feel free to run `dep ensure` and add this.
