### ISSUE TITLE
[Feature Request] Possibility to add HTTP Headers to Invoke Function

### ISSUE THREAD

**Issue by sticreations** [openfaas-incubator/connector-sdk#37]
It would be a blast to have the option to add HTTP Headers to the Invoke function. (To use Opentracing via Headers)

**Comment by sticreations** [comment]
Sorry, just seen that i can send a Request with ctx...

**Comment by alexellis** [comment]
Would you like to leave a code example for future Googlers?

Thanks to @bmcstdio for adding the context. cc @LucasRoesler re tracing.
