### ISSUE TITLE
Add retry/durability options if Invoke() fails

### ISSUE THREAD

**Issue by embano1** [openfaas-incubator/connector-sdk#5]
Currently `Invoke()` only prints out errors but does not return any errors to the caller, i.e. the initiating connector. It is exactly-once messaging, which the [docs](https://docs.openfaas.com/reference/triggers/) are not clear about. 

```go
func (i *Invoker) Invoke(topicMap *TopicMap, topic string, message *[]byte) {
...
			log.Printf("Invoke function: %s", matchedFunction)

			gwURL := fmt.Sprintf("%s/function/%s", i.GatewayURL, matchedFunction)
			reader := bytes.NewReader(*message)

			body, statusCode, doErr := invokefunction(i.Client, gwURL, reader)

			if doErr != nil {
				log.Printf("Unable to invoke from %s, error: %s\n", matchedFunction, doErr)
				return
			}
```
[Code Path](https://github.com/openfaas-incubator/connector-sdk/blob/bb7e84c27a54ab641317d26961300ed92aea739e/types/invoker.go#L18)

There could be many reasons why an `Invoke` would fail, e.g. OpenFaaS down/maintenance, network hiccups, issues with the receiving function (downstream down, bug), etc.

Returning an error would help the initiating connector to queue the event/call and retry as per its own needs.

**Comment by Templum** [comment]
PR #4 does touch on some of the points.

**Comment by martindekov** [comment]
Hey there @embano1 I saw Alex merged [PR](https://github.com/openfaas-incubator/connector-sdk/pull/8/files) which I think references your request/this issue. Can you take a look? Thanks

**Comment by embano1** [comment]
All good, thanks.
